### ISSUE TITLE
support devices behind megaraid controllers

### ISSUE THREAD

**Issue by evanrich** [ajclark/datadog-smartmon#15]
when using smartctl, you need to pass in -d megaraid,x to indicate the drive to collect, so say you have two drives, you would do something like

```
smartctl -A /dev/sda -d megaraid,0
smartctl -A /dev/sda -d megaraid,1
```

can this be updated to support arrays?

**Comment by evanrich** [comment]
nevermind i just read the python file and it does work already.  Thanks!

**Comment by evanrich** [comment]
going to add how I implemented this because you saved me a TON of work.   We use saltstack to deploy changes on machines, here's the salt state in case anyone else uses salt and wants to apply this:
```
{% if grains['os'] == 'Ubuntu' and grains['manufacturer'] == 'Dell Inc.' -%}

#ensure that the smartmontools pacckage is installed
base-drive_health-smartmontools:
  pkg.installed:
    - name: smartmontools

base-drive_health-change-smartctl-perms:
  cmd.run:
    - name: chmod +s /usr/sbin/smartctl
    - unless: test -u /usr/sbin/smartctl
    - require:
      - pkg: base-drive_health-smartmontools

base-drive_health-install-pysmart:
  pip.installed:
    - name: pysmart
    - bin_env: /opt/datadog-agent/embedded/bin/pip
    - user: dd-agent
    - cwd: /opt/datadog-agent

# install the smartmon.py in the /etc/datadog-agent/checks.d directory
base-drive_health-install-pythoncode:
  file.managed:
    - name: /etc/datadog-agent/checks.d/smartmon.py
    - source: salt://base/files/smartmon.py
    - user: dd-agent
    - group: dd-agent
    - mode: 644
    - require:
      - pip: base-drive_health-install-pysmart

# install the smartmon.yaml in the /etc/datadog-agent/conf.d directory
base-drive_health-install-yaml:
  file.managed:
    - name: /etc/datadog-agent/conf.d/smartmon.yaml
    - source: salt://base/files/smartmon.yaml
    - user: dd-agent
    - group: dd-agent
    - mode: 644
    - require:
      - file: base-drive_health-install-pythoncode

# restart the datadog-agent service if changes are made
base-drive_health-restart-agent:
  service.running:
    - name: datadog-agent
    - watch:
      - file: base-drive_health-install-yaml
      - file: base-drive_health-install-pythoncode
{% endif %}
```

small little contribution to your amazing contribution.  Thanks!
